# Simulation settings for using moveit_sim_controllers
moveit_sim_hw_interface:
  joint_model_group: panda_arm
  joint_model_group_pose: ready
# Settings for ros_control_boilerplate control loop
generic_hw_control_loop:
  loop_hz: 300
  cycle_time_error_threshold: 0.01
# Settings for ros_control hardware interface
hardware_interface:
  joints:
    - panda_joint1
    - panda_joint2
    - panda_joint3
    - panda_joint4
    - panda_joint5
    - panda_joint6
    - panda_joint7
    - panda_finger_joint1
  sim_control_mode: 1  # 0: position, 1: velocity
